name: freezer
description: >
  Automatically generates object classes supported by the freezed library
  directly from JSON files.
version: 0.3.0
repository: https://github.com/myConsciousness/freezer
issue_tracker: https://github.com/myConsciousness/freezer/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build_runner: ^2.2.0
  dart_style: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
